### PR TITLE
Upgrade jupyterlab depedencies to work with jupyterlab 0.33.0

### PR DESCRIPTION
**Pull request by gnestor**
Closes https://github.com/jupyterlab/jupyterlab-monaco/issues/15

@jasongrout This builds correctly and passes jupyterlab build, I'm running into the following runtime error:

```
TypeError: Class constructor ABCWidgetFactory cannot be invoked without 'new'
    at new MonacoEditorFactory (index.js:124)
    at activate (index.js:149)
    at index.js:147
```

### CODE REVIEW

**Comment by ian-r-rose** [comment]
This error is a consequence of our change to ES6. If you change the `target` in the `tsconfig.json` to ES6 it should be fixed.

**Comment by gnestor** [comment]
Thanks @ian-r-rose! It's working now 👍

**Comment by ian-r-rose** [comment]
LGTM, thanks @gnestor

**Comment by jasongrout** [comment]
Thanks!

**Pull request merged**
