### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by TiemenSch**
Added explanatory paragraphs (similar to comment in #6)
Added screenshots (taken from https://github.com/jupyterlab/jupyterlab/issues/135#issuecomment-382195889), as requested in #8.

### CODE REVIEW

**Comment by Naereen** [comment]
Great to have screenshots!
My habit is to store them as file in the git repository (e.g., in `screenshots/` folder), rather than let the https://user-images.githubusercontent.com/ site host them.
This way, if the git has to be moved somewhere else, the documentation is still complete.

**Comment by jasongrout** [comment]
Thanks! I agree with @Naereen about putting the screenshots in this repo, if they're not too large (they look small). Would you be able to do that, or should we do that in a different PR?

**Comment by TiemenSch** [comment]
Is it OK like this? Not sure if there are any guidelines on file naming.

**Comment by jasongrout** [comment]
Thanks!

**Comment by jasongrout** [comment]
If either of you want to work on pushing this extension forward, let me know and I can give you push access to the repo.

**Comment by TiemenSch** [comment]
As it's publicly on Github, I'm fine with forking it for now. I would be interested in seeing where an abstract editor interface attempt would end up.

I fear my lack of knowledge of JavaScript/TypeScript will prohibit me from making a lot of progress in the near future, though. I'm much more comfortable on the Python end of things, but we'll see.

**Pull request merged**
